apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Full Lifecycle
    categories: Developer Tools, Integration & Delivery
    certified: "true"
    containerImage: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-operator-rhel9
    description: Builds for Red Hat OpenShift is a framework for building container
      images on Kubernetes.
    features.operators.openshift.io/cnf: "false"
    features.operators.openshift.io/cni: "false"
    features.operators.openshift.io/csi: "true"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "false"
    features.operators.openshift.io/proxy-aware: "false"
    features.operators.openshift.io/tls-profiles: "false"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    operatorframework.io/suggested-namespace: openshift-builds
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform", "OpenShift
      Platform Plus"]'
    repository: https://github.com/shipwright-io/operator
    support: Red Hat
  labels:
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.arm64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
  name: openshift-builds-operator.v0.0.0
  namespace: openshift-builds
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ShipwrightBuild represents the deployment of Shipwright's build
        controller on a Kubernetes cluster.
      displayName: Shipwright Build
      kind: ShipwrightBuild
      name: shipwrightbuilds.operator.shipwright.io
      version: v1alpha1
    - description: OpenShiftBuild describes the desired state of Builds for OpenShift,
        and the status of all deployed components.
      displayName: Open Shift Build
      kind: OpenShiftBuild
      name: openshiftbuilds.operator.openshift.io
      version: v1alpha1
    required:
    - kind: TektonConfig
      name: tektonconfigs.operator.tekton.dev
      version: v1alpha1
  description: "Builds for Red Hat OpenShift is an extensible build framework based
    on the Shipwright project, \nwhich you can use to build container images on an
    OpenShift Container Platform cluster. \nYou can build container images from source
    code and Dockerfile by using image build tools, \nsuch as Source-to-Image (S2I)
    and Buildah. You can create and apply build resources, view logs of build runs,
    \nand manage builds in your OpenShift Container Platform namespaces.\nRead more:
    [https://shipwright.io](https://shipwright.io)\n\n## Features\n\n* Standard Kubernetes-native
    API for building container images from source code and Dockerfile\n\n* Support
    for Source-to-Image (S2I) and Buildah build strategies\n\n* Extensibility with
    your own custom build strategies\n\n* Execution of builds from source code in
    a local directory\n\n* Shipwright CLI for creating and viewing logs, and managing
    builds on the cluster\n\n* Integrated user experience with the Developer perspective
    of the OpenShift Container Platform web console\n"
  displayName: Builds for Red Hat OpenShift Operator
  icon:
  - base64data: |
      PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmlld0JveD0iMCAwIDM4IDM4Ij48ZGVmcz48c3R5bGU+LmN7ZmlsbDojZTAwO30uZHtmaWxsOiNmZmY7fS5le2ZpbGw6I2UwZTBlMDt9PC9zdHlsZT48L2RlZnM+PGcgaWQ9ImEiPjxnPjxyZWN0IGNsYXNzPSJkIiB4PSIxIiB5PSIxIiB3aWR0aD0iMzYiIGhlaWdodD0iMzYiIHJ4PSI5IiByeT0iOSIvPjxwYXRoIGNsYXNzPSJlIiBkPSJNMjgsMi4yNWM0LjI3LDAsNy43NSwzLjQ4LDcuNzUsNy43NVYyOGMwLDQuMjctMy40OCw3Ljc1LTcuNzUsNy43NUgxMGMtNC4yNywwLTcuNzUtMy40OC03Ljc1LTcuNzVWMTBjMC00LjI3LDMuNDgtNy43NSw3Ljc1LTcuNzVIMjhtMC0xLjI1SDEwQzUuMDMsMSwxLDUuMDMsMSwxMFYyOGMwLDQuOTcsNC4wMyw5LDksOUgyOGM0Ljk3LDAsOS00LjAzLDktOVYxMGMwLTQuOTctNC4wMy05LTktOWgwWiIvPjwvZz48L2c+PGcgaWQ9ImIiPjxnPjxjaXJjbGUgY2xhc3M9ImQiIGN4PSIxOSIgY3k9IjE5IiByPSI3LjM4Ii8+PHBhdGggY2xhc3M9ImMiIGQ9Ik0xOSwxMC4zOGMtNC43NiwwLTguNjIsMy44Ny04LjYyLDguNjJzMy44Nyw4LjYyLDguNjIsOC42Miw4LjYyLTMuODcsOC42Mi04LjYyLTMuODctOC42Mi04LjYyLTguNjJabTAsMTZjLTQuMDcsMC03LjM4LTMuMzEtNy4zOC03LjM4czMuMzEtNy4zOCw3LjM4LTcuMzgsNy4zOCwzLjMxLDcuMzgsNy4zOC0zLjMxLDcuMzgtNy4zOCw3LjM4WiIvPjwvZz48Zz48cGF0aCBjbGFzcz0iZCIgZD0iTTE1LjM4LDE2YzAtLjM1LC4yOC0uNjIsLjYyLS42Mmg1LjM4di00Ljc1SDEwLjYydjEwLjc1aDQuNzV2LTUuMzhaIi8+PHJlY3QgY2xhc3M9ImQiIHg9IjE2LjYyIiB5PSIxNi42MiIgd2lkdGg9IjEwLjc1IiBoZWlnaHQ9IjEwLjc1Ii8+PHBhdGggZD0iTTI4LDE1LjM4aC01LjM4di01LjM4YzAtLjM1LS4yOC0uNjItLjYyLS42MkgxMGMtLjM1LDAtLjYyLC4yOC0uNjIsLjYydjEyYzAsLjM1LC4yOCwuNjIsLjYyLC42Mmg1LjM4djUuMzhjMCwuMzUsLjI4LC42MiwuNjIsLjYyaDEyYy4zNCwwLC42Mi0uMjgsLjYyLS42MnYtMTJjMC0uMzUtLjI4LS42Mi0uNjItLjYyWm0tLjYyLDEyaC0xMC43NXYtMTAuNzVoMTAuNzV2MTAuNzVaTTEwLjYyLDEwLjYyaDEwLjc1djQuNzVoLTUuMzhjLS4zNSwwLS42MiwuMjgtLjYyLC42MnY1LjM4aC00Ljc1VjEwLjYyWiIvPjwvZz48Zz48cG9seWdvbiBjbGFzcz0iZCIgcG9pbnRzPSIxOS44OCAyMiAyMSAyMy4xMiAyMSAyMC44OCAxOS44OCAyMiIvPjxwYXRoIGNsYXNzPSJjIiBkPSJNMjEsMjAuODhsLjQ0LS40NGMuMjQtLjI0LC4yNC0uNjQsMC0uODgtLjI0LS4yNC0uNjQtLjI0LS44OCwwbC0yLDJjLS4yNCwuMjQtLjI0LC42NCwwLC44OGwyLDJjLjEyLC4xMiwuMjgsLjE4LC40NCwuMThzLjMyLS4wNiwuNDQtLjE4Yy4yNC0uMjQsLjI0LS42NCwwLS44OGwtLjQ0LS40NC0xLjEyLTEuMTIsMS4xMi0xLjEyWiIvPjxwb2x5Z29uIGNsYXNzPSJkIiBwb2ludHM9IjIzIDIwLjg4IDIzIDIzLjEyIDI0LjEyIDIyIDIzIDIwLjg4Ii8+PHBhdGggY2xhc3M9ImMiIGQ9Ik0yNS40NCwyMS41NmwtMi0yYy0uMjQtLjI0LS42NC0uMjQtLjg4LDAtLjI0LC4yNC0uMjQsLjY0LDAsLjg4bC40NCwuNDQsMS4xMiwxLjEyLTEuMTIsMS4xMi0uNDQsLjQ0Yy0uMjQsLjI0LS4yNCwuNjQsMCwuODgsLjEyLC4xMiwuMjgsLjE4LC40NCwuMThzLjMyLS4wNiwuNDQtLjE4bDItMmMuMjQtLjI0LC4yNC0uNjQsMC0uODhaIi8+PC9nPjwvZz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - build
  - shipwright
  - tekton
  - cicd
  links:
  - name: Documentation
    url: https://docs.openshift.com/builds/latest/about/overview-openshift-builds.html
  - name: Builds for Openshift
    url: https://github.com/redhat-openshift-builds/operator
  maintainers:
  - email: openshift-builds@redhat.com
    name: Red Hat OpenShift Builds Team
  maturity: stable
  minKubeVersion: 1.25.0
  provider:
    name: Red Hat
    url: https://www.redhat.com
  relatedImages:
  - image: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-operator@sha256:99481b5ebe12e4b0f91f5c2c94218276ff8b09ba19a8ff4dbaef5067ce8a0b47
    name: OPENSHIFT_BUILDS_OPERATOR
  - image: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-controller@sha256:d8f0a2e2cea4ec2523522f88dc5b29b99635b156c0dd716241124b21708efcb7
    name: OPENSHIFT_BUILDS_CONTROLLER
  - image: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-git-cloner@sha256:efda8e9dad994f90bfb8fba6c7ec75792018ac8c28d0136eb518ae62e32a0519
    name: OPENSHIFT_BUILDS_GIT_CLONER
  - image: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-image-processing@sha256:8bcd515f19b53edcc47ae3e578f0f48d285b4668bae68066322b41c836a61288
    name: OPENSHIFT_BUILDS_IMAGE_PROCESSING
  - image: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-image-bundler@sha256:e707f4096929f93e6e70150dd50ce2ea525966f9e85c67c2dd10b58ab3e88203
    name: OPENSHIFT_BUILDS_IMAGE_BUNDLER
  - image: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-waiters@sha256:5dd6a22eac7b89da21f0f4643555e88afdee04a28cd9910e38867e8c5de042e4
    name: OPENSHIFT_BUILDS_WAITER
  - image: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-webhook@sha256:b0b6288d5d32df3fadcacccafd415898e0664ffd385a02d793797786232bc3d9
    name: OPENSHIFT_BUILDS_WEBHOOK
  - image: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-shared-resource-webhook@sha256:953d91f47bd25600016aea7661956316333b6473cbdcdde7f2a234b321d03536
    name: OPENSHIFT_BUILDS_SHARED_RESOURCE_WEBHOOK
  - image: quay.io/redhat-user-workloads/rh-openshift-builds-tenant/openshift-builds/openshift-builds-shared-resource@sha256:439ac450d3353894835bd46d181944d268ddf53926bb60e73d9374f30d3bcc17
    name: OPENSHIFT_BUILDS_SHARED_RESOURCE
  - image: registry.redhat.io/openshift4/ose-csi-node-driver-registrar@sha256:98341f0b80eeb6064540b61626acb6c6772c1e5c6991b67cfec3768cf459da14
    name: OPENSHIFT_BUILDS_SHARED_RESOURCE_NODE_REGISTRAR
  - image: registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:97cade2c1ee468261aec5400728c8d44de387b459134aec7a4c3b5ec5a335d2c
    name: OPENSHIFT_BUILDS_KUBE_RBAC_PROXY
  version: 1.1.0
